Project initialization script

diff --git a/bin/setup-composer-auth b/bin/setup-composer-auth
--- a/bin/setup-composer-auth
+++ b/bin/setup-composer-auth
@@ -1,53 +1,46 @@
 #!/usr/bin/env bash
 
-# Initializes composer credentials (github token, magento repository access).
+# Initializes the composer.env file.
 
-cd "$( dirname "${BASH_SOURCE[0]}" )"
+set -e
+
+cd "$( dirname "${BASH_SOURCE:-$0}}" )"
 cd ..
 
-MAGENTO_USERNAME_PROP="http-basic.repo.magento.com.username"
-MAGENTO_PASSWORD_PROP="http-basic.repo.magento.com.password"
-hash composer 2>/dev/null && IS_COMPOSER_ON_HOST=true
+. ./bin/deps/utils.sh
 
-PUBLIC_KEY="$(bin/cli composer config --global $MAGENTO_USERNAME_PROP 2>/dev/null)"
-PRIVATE_KEY="$(bin/cli composer config --global $MAGENTO_PASSWORD_PROP 2>/dev/null)"
+########
+# Step 1 - Create env/composer.env if it does not already exist
+########
 
-echo $PUBLIC_KEY
-echo $PRIVATE_KEY
-exit
+if [ ! -f "env/composer.env" ]; then
+    if [ ! -f "env/composer.env.sample" ]; then
+        echo "${RED}The file env/composer.env cannot be created because the template file env/composer.env.sample doesn't exist.${RESET}"
+        exit 1
+    fi
 
-if [ -n "$PUBLIC_KEY" ] && [ -n "$PRIVATE_KEY" ]; then
-    echo "Composer auth has already been set up."
-    exit 0
+    cp "env/composer.env.sample" "env/composer.env"
+    echo "${GREEN}✓ Created file env/composer.env.${RESET}"
+else
+    . ./env/composer.env
 fi
 
-if [ $IS_COMPOSER_ON_HOST ]; then
-    PUBLIC_KEY="$(composer config --global $MAGENTO_USERNAME_PROP 2>/dev/null)"
-    PRIVATE_KEY="$(composer config --global $MAGENTO_PASSWORD_PROP 2>/dev/null)"
+########
+# Step 2 - Fetch composer github token from host
+########
+
+if [ -z "$COMPOSER_GITHUB_TOKEN" ]; then
+    COMPOSER_GITHUB_PATH="github-oauth.github.com"
+
+    if command -v composer > /dev/null; then
+        COMPOSER_GITHUB_TOKEN="$(composer config --global $COMPOSER_GITHUB_PATH 2>/dev/null)"
+
+        if [ -n "$COMPOSER_GITHUB_TOKEN" ]; then
+            sed -i "s/^COMPOSER_GITHUB_TOKEN=.*/COMPOSER_GITHUB_TOKEN=${COMPOSER_GITHUB_TOKEN}/g" env/composer.env
+            echo "${GREEN}✓ The GitHub token \"$COMPOSER_GITHUB_TOKEN\" was saved saved in the env/composer.env file.${RESET}"
+        else
+            echo "No GitHub token found on the host."
+        fi
+    fi
 fi
 
-echo $PUBLIC_KEY
-echo $PRIVATE_KEY
-exit
-
-if [ -z "$PUBLIC_KEY" ] || [ -z "$PRIVATE_KEY" ]; then
-    exec < /dev/tty
-    echo
-    echo "Composer authentication required (repo.magento.com public and private keys):"
-    read -r -p "    Username: " PUBLIC_KEY
-    read -r -p "    Password: " PRIVATE_KEY
-    echo
-    exec <&-
-fi
-
-if [ -z "$PUBLIC_KEY" ] || [ -z "$PRIVATE_KEY" ]; then
-    echo "Please setup Composer auth for repo.magento.com to continue." && exit 1
-fi
-
-# Output must be piped otherwise file descriptor errors occur. Carriage returns?
-echo "composer config --global http-basic.repo.magento.com ${PUBLIC_KEY} ${PRIVATE_KEY}" | bin/clinotty bash -
-
-# Also make sure alternate auth.json is setup (Magento uses this internally)
-./bin/composer [ -d "./var/composer_home" ] && ./bin/composer cp /var/www/.composer/auth.json ./var/composer_home/auth.json
-
-echo "Composer auth has been set up."
